name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build React Test Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test -- --coverage

  build-push-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          region: us-east-1
          version_label: v${{ github.run_number }}
          deployment_package: deploy.zip